### PR TITLE
[MIG] iot_output_oca: Migration to 14.0

### PR DESCRIPTION
**Pull request by etobella**
Migration script for changed field names added

@lubusax

### CODE REVIEW

**Review by lubusax — APPROVED** [review]

**Review by lubusax — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You have to rename model and table for `iot.communication.system`.

**Comment by etobella** [comment]
It was renamed on iot_oca. It is really necessary to do it here then?

**Review by pedrobaeza — APPROVED** [review]
Sorry, my fault seeing bad here

**Pull request merged**
