### PR TITLE
[12.0][MIG] iot_option_oca

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
I did not rename the module to make easier the migration later on

ping @ForgeFlow
ping @etobella 
ping @lubusax

Depends on:
- [x] https://github.com/OCA/iot/pull/55
- [ ] https://github.com/OCA/iot/pull/56

### CODE REVIEW

**Review by lubusax — APPROVED** [review]
Funcional tests on a RAS device OK

**Review by lubusax — APPROVED** [review]
Funcional tests on a RAS device OK

**Comment by etobella** [comment]
Can you rebase?

**Comment by AaronHForgeFlow** [comment]
rebased! :innocent:

**Review by etobella — APPROVED** [review]
Technical review

**Pull request merged**
