### PR TITLE
[17.0][MIG] iot_template_oca

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Review by MRomeera — APPROVED** [review]
LGTM

**Review by AntoniRomera — APPROVED** [review]
LGTM

**Comment by FernandoRomera** [comment]
@etobella 
when you can review, I would appreciate it.

**Comment by AntoniRomera** [comment]
@OCA/iot-maintainers anyone can review?

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
