### PR TITLE
[MIG] iot_oca: migration to 16.0

### PR DESCRIPTION
**Pull request by mostafabarmshory**
Move from 15.0 to 16.0

### CODE REVIEW

**Comment by mostafabarmshory** [comment]
Dear @etobella 

I`ve created the new PR and squashed all commits. My last PR is here:

https://github.com/OCA/iot/pull/84

Would you accept the PR, please?

**Comment by etobella** [comment]
You don't need to create a new PR. Just do a git push --force. Actually it is better to keep the original pr in order to simplify review (for next time)

I will review it next week

**Comment by etobella** [comment]
Can you rename the commit in a proper way:

`[MIG] iot_oca: migration to 16.0`

In order to do that, you can do the following commands:

git commit --amend
edit the message
git push --force

**Comment by mostafabarmshory** [comment]
@etobella 
commands fail with Windows. I have to follow yours in Ubuntu. 

Would you check the PR, please?

**Comment by etobella** [comment]
You did nothing.... I mean, you created an empty commits. You need to squash all yout migration commits together.

**Comment by mostafabarmshory** [comment]
Dear @etobella,
I  squashed my last 6 commits. It seems ok now.

**Review by etobella — APPROVED** [review]
Technically LGTM

**Comment by etobella** [comment]
Something is wrong with the history....

I can close the PR and make it myself keeping your Migration commit if it is OK with you...

**Review by etobella — CHANGES_REQUESTED** [review]
Some comits are empty...

**Comment by etobella** [comment]
I already made the PR, I kept you as contributor.

As you can see, most of your migration commit disappeared, as the files where no changed. Also, there are only 19 commits (I merged the translation commits from the same author and language)

https://github.com/OCA/iot/pull/86

**Pull request closed without merging**
