### PR TITLE
[MIG] iot_oca

### PR DESCRIPTION
**Pull request by olgamarcocb**
Standard Migration

Change of module name using git filter-branch

@etobella

### CODE REVIEW

**Comment by etobella** [comment]
I am wondering if it is necessary to rename it to `iot_oca`, following the same logic than `edi`

@pedrobaeza WDYT?

**Comment by pedrobaeza** [comment]
Yes, I think so for avoiding to be masked.

**Review by etobella — APPROVED** [review]
LGTM

Tested locally

**Pull request merged**
