### PR TITLE
[16.0][MIG] iot_template_oca

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Standard migration

cc @ForgeFlow

cc @lubusax

### CODE REVIEW

**Review by lubusax — APPROVED** [review]
functional review 👍🏾

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
@etobella can you have a look at this?

**Review by etobella — APPROVED** [review]
/ocabot merge  nobump

**Pull request merged**
