### PR TITLE
[17.0][MIG] iot_amqp_oca: Migration to 17.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Review by MRomeera — APPROVED** [review]
LGTM

**Review by AntoniRomera — APPROVED** [review]
LGTM

**Comment by FernandoRomera** [comment]
@etobella 
when you can review, I would appreciate it.

**Comment by FernandoRomera** [comment]
@OCA/iot-maintainers anyone can review?

**Comment by AntoniRomera** [comment]
@OCA/iot-maintainers Can anyone review it?

**Review by etobella — APPROVED** [review]
/ocabot migration it_amqp_oca

**Pull request merged**
