### PR TITLE
[16.0] [iot] merge with odoo 15

### PR DESCRIPTION
**Pull request by mostafabarmshory**
The main goal is to merge with odoo 15.0 at the first step. Then We can add more features.

### CODE REVIEW

**Comment by mostafabarmshory** [comment]
Dear all, 

I move to odoo 16.0 and check all unit tests. 
It's okay right now.
I want to add more tests and a little document to the project.

But before that, I need to know if the current state is ok.

@etobella

**Review by etobella — CHANGES_REQUESTED** [review]
You did not follow the standard migration rules

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

Can you try to follow them before asking for reviews? If you don't do that, it is too hard to review, also, you are not keeping history and authors. That is important

**Comment by mostafabarmshory** [comment]
> You did not follow the standard migration rules
> 
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0
> 
> Can you try to follow them before asking for reviews? If you don't do that, it is too hard to review, also, you are not keeping history and authors. That is important

Ok, let me check the rule and try to update the pull request.

**Comment by pedrobaeza** [comment]
And please only one module per PR.

**Comment by mostafabarmshory** [comment]
Seams I have to close the request and start from the beginning!

**Comment by mostafabarmshory** [comment]
the PR does not satisfy with the oca rules. I will start a new one.

**Pull request closed without merging**
